### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [jenterkin/vim-autosource#3]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by jenterkin** [comment]
Thanks for the suggestion. I didn't bother since I didn't think anyone else would use this, but seeing as I just reviewed a substantial PR that may not be the case. I'm partial to MIT so I just added that to the repo.

**Comment by ii14** [comment]
In GPL (I believe in AGPL too) you have to contribute changes back only if you're redistributing the software. Which, in case of GPL, is the same thing.

Maybe that's just my opinion, but I find using those licenses pointless for vim plugins.
